README.md
defaults/main.yml
tasks/handle_container_conf_d.yml
tasks/handle_policy_json.yml
tasks/handle_storage_conf.yml
tasks/main.yml
tests/tests_basic.yml
tests/tests_config_files.yml
vars/main.yml

Add support for storage.conf and policy.json
Fix user support - have to get user home dir and add that to paths
Separate config file testing to another test file - too difficult
to figure out which options will interfere with regular container
testing.

Add support for storage.conf,policy.json; fix user config support

---

tasks/create_update_kube_spec.yml
tests/tests_basic.yml
vars/main.yml

Do not set a default mode when creating host directories.  Instead,
the role will use whatever the `file` module uses when mode is not
specified.  In order to set a different default mode, the user will
need to figure out how to set the default for the `file` module.
Users can also use `podman_host_directories` to explicitly set the
mode.

remove default directory mode

---

tasks/main.yml

This does not require sudo/root access in contrast to the package module

Check for required packages in package_facts

---

README.md
meta/main.yml
tasks/handle_kube_spec.yml
tasks/handle_user_group.yml
tasks/main.yml
tests/roles/caller/tasks/main.yml

Ensure that the specified user is present in `/etc/subuid`.
Ensure that the specified group is present in `/etc/subgid`.
Refactor the user/group checking so that it can be used from
multiple contexts.
Clean up some quoting and ansible-lint issues.

add checking for subuid, subgid

---

CHANGELOG.md

[1.1.0] - 2022-12-12
--------------------
- add checking for subuid, subgid
Ensure that the specified user is present in `/etc/subuid`.
Ensure that the specified group is present in `/etc/subgid`.
- none
- none

Version 1.1.0 - CHANGELOG.md [citest skip]

---

.github/workflows/woke.yml

Add a check for usage of terms and language that is considered non-inclusive. We are using the woke tool for this with a wordlist that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml

Add check for non-inclusive language

---

tasks/create_update_kube_spec.yml

https://github.com/linux-system-roles/podman/issues/39
Using `0700` and `0600` are too restrictive.  Make the directory
and files world readable.

Ease permissions on kube spec dir and files

---

templates/get_ansible_managed.j2
templates/toml.j2

Add role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.

Fingerprint RHEL System Role managed config files

---

tasks/cleanup_kube_spec.yml
tasks/create_update_kube_spec.yml
tasks/handle_kube_spec.yml
tests/tests_basic.yml

ansible-lint now requires the use of changed_when even with
conditional tasks

ansible-lint - changed_when required even with conditional tasks

---

tests/tests_basic.yml

Use `podman pod exists` to check if pods are running.  This
should fix the tests on Fedora.

test: use podman pod exists to check if pods absent/stopped

---

tests/tests_config_files.yml

Fedora 37 tests fail with an error that `graphroot` is required.
Fix it by adding `graphroot` for storage conf tests.

fix: graphroot required in storage.conf on Fedora 37

---

tests/tasks/check_header.yml
tests/templates/get_ansible_managed.j2
tests/tests_config_files.yml

Add the following files: tests/tasks/check_header.yml and
tests/templates/get_ansible_managed.j2.
Use check_header.yml to check generated files for the ansible_managed
and fingerprint headers.
check_header.yml takes these parameters.  `fingerprint` is required,
and one of `__file` or `__file_content`:
* `__file` - the full path of the file to check e.g. `/etc/realmd.conf`
* `__file_content` - the output of `slurp` of the file
* `__fingerprint` - required - the fingerprint string `system_role:$ROLENAME` e.g.
`__fingerprint: "system_role:postfix"`
* `__comment_type` - optional, default `plain` - the type of comments used
e.g. `__comment_type: c` for C/C++-style comments.  `plain` uses `#`.
See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#adding-comments-to-fi …

test: check generated files for ansible_managed, fingerprint

---

tasks/handle_kube_spec.yml

Jinja 2.7 does not support the `in` test, so use `match` instead
with an extended regexp.

fix: Use match instead of in for test for jinja 2.7 support

---

tests/tests_basic.yml

I guess ansible-core 2.15 does not export `vars` defined
in a `include_role` keyword in a play to other task sections in
the play.  The fix is to declare the variable in the `vars`
at the `block` level.

fix: make role work on ansible-core 2.15

---

README.md
defaults/main.yml
tasks/cleanup_quadlet_spec.yml
tasks/create_update_kube_spec.yml
tasks/create_update_quadlet_spec.yml
tasks/handle_kube_spec.yml
tasks/handle_quadlet_spec.yml
tests/tests_basic.yml
tests/tests_config_files.yml
tests/tests_quadlet_basic.yml
tests/tests_quadlet_demo.yml

Feature: Add `podman_pull_image` - if `false`, do not pull the image before trying
to use it. Add `podman_continue_if_pull_fails` - continue with the role if the image
pull fails.
Reason: The managed node might be isolated and unable to pull images.  The managed
node might be pre-built with images already present.  Users need to have more control
about what happens in these situations.
Result: User can control when/how images are pulled by units.

feat: allow not pulling images, continue if pull fails

---

tasks/handle_quadlet_spec.yml
tasks/handle_registries_conf_d.yml
templates/toml.j2
tests/tests_config_files.yml

Cause: The toml code was trying to put global options (options not in a section)
into a section.
Consequence: The podman role gave errors when using global options.
Fix: The toml code will handle global options separately from options which are
placed into sections.
Result: The podman role config files can handle both global options and options
which are in sections.

fix: support global options in config files

---

README.md
tasks/handle_user_group.yml
vars/RedHat.yml
vars/RedHat_8.yml
vars/main.yml

Use the command `getsubids` to check the subuid and subgid if
available.  This allows the use of identity management to provide
the subuid and subgid.

refactor: use getsubids to check subuid and subgid

---

.ansible-lint
.ostree/README.md
.ostree/get_ostree_data.sh
.ostree/packages-runtime-CentOS.txt
.ostree/packages-runtime-RedHat-8.txt
.ostree/packages-runtime.txt
.ostree/roles-runtime.txt
.ostree/roles-testing.txt
.sanity-ansible-ignore-2.14.txt
.sanity-ansible-ignore-2.15.txt
README-ostree.md
meta/collection-requirements.yml
tasks/set_vars.yml

Feature: Allow running and testing the role with ostree managed nodes.
Reason: We have users who want to use the role to manage ostree
systems.
Result: Users can use the role to manage ostree managed nodes.

feat: support for ostree systems

---

.ostree/get_ostree_data.sh
.sanity-ansible-ignore-2.14.txt
.sanity-ansible-ignore-2.15.txt

Use the `#!/usr/bin/env bash` shebang which is ansible-test friendly.
This means we can remove get_ostree_data.sh from the .sanity* files.
This also means we can remove the .sanity* files if we do not need
them otherwise.
Rename `pth` to `path` in honor of nscott

refactor: get_ostree_data.sh use env shebang - remove from .sanity*

---

.markdownlint.yaml
tests/files/envoy-proxy-configmap.yml
tests/tests_include_vars_from_parent.yml

Fix yamllint issue with markdownlint config
Add cleanup for tests_include_vars_from_parent.yml

ci: support ansible-lint and ansible-test 2.16

---

tasks/handle_quadlet_spec.yml
tests/tests_quadlet_basic.yml
tests/tests_quadlet_demo.yml

Cause: The code was using a volume quadlet service name of basename.volume.
Consequence: Attempting to start this service name would give an error such
as "Could not find the requested service NAME.volume: host"
Fix: The volume quadlet service name is changed to basename-volume.service
Result: The volume service can be started with no errors.
See https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#volume-units-volume
for more info.

fix: name of volume quadlet service should be basename-volume.service

---

tasks/handle_secret.yml
tests/tests_quadlet_basic.yml

Cause: Ansible is somehow converting JSON strings to the corresponding
JSON object if the value is used in a loop and the value is used
like `data: "{{ value }}"`
Consequence: You cannot pass JSON strings as secrets and have the
value preserved.
Fix: Cast the data value to a string when passing to the podman_secret
module.
Result: JSON strings are preserved as-is for use in secrets.
Github issue: https://github.com/linux-system-roles/podman/issues/121

fix: cast secret data to string in order to allow JSON valued strings

---

tests/tests_quadlet_basic.yml

The tasks which handle secrets should be marked `no_log: true`.
Data used for secrets should not be logged.  In order to test
this, you can use the environment variable
`SYSTEM_ROLES_PODMAN_PASSWORD` which will use this as the secret
data for the test.  Then, you can search for this string in
the Ansible output/logs.  Any hit means secret data is being
leaked.
```bash
SYSTEM_ROLES_PODMAN_PASSWORD=$(openssl rand -hex 32)
SYSTEM_ROLES_PODMAN_PASSWORD="${SYSTEM_ROLES_PODMAN_PASSWORD}" \
tox -e qemu-ansible-core-2.16 -- --image-name centos-9 --log-level debug \
tests/tests_quadlet_basic.yml > output 2>&1
grep "${SYSTEM_ROLES_PODMAN_PASSWORD}" output
```

test: allow testing to see if secrets are logged

---

defaults/main.yml
tasks/cancel_linger.yml
tasks/cleanup_kube_spec.yml
tasks/cleanup_quadlet_spec.yml
tasks/create_update_kube_spec.yml
tasks/create_update_quadlet_spec.yml
tasks/handle_secret.yml
tasks/main.yml
tasks/manage_linger.yml
templates/toml.j2
tests/tests_basic.yml
tests/tests_config_files.yml
tests/tests_include_vars_from_parent.yml
tests/tests_quadlet_basic.yml
tests/tests_quadlet_demo.yml

Cause: The role was not always enabling user lingering before
creating resources, and not always canceling lingering after
removing resources.
Consequence: The role would give errors if attempting to create
a secret or other resource requiring lingering, or would leave
lingering enabled after removing resources.
Fix: Centralize linger handling and keep track of users which
may need linger canceling.  Ensure linger is canceled for all
users if all of that user's resources are removed and linger is
no longer needed.
Result: Resources for rootless users are always created properly.
Lingering is always canceled when no longer needed.

fix: ensure user linger is enabled and disabled correctly

---

tasks/cancel_linger.yml
tests/tests_basic.yml

Cause: When processing a list of kube or quadlet items, the
code was using the user id associated with the list, not the
item, to specify the linger filename.
Consequence: The linger file does not exist, so the code
does not cancel linger for the actual user.
Fix: Use the correct username to construct the linger filename.
Result: Lingering is cancelled for the correct users.
QE: The test is now in tests_basic.yml

fix: use correct user for cancel linger file name

---

tests/tests_basic.yml

Do not check if there is a linger file for root.

test: do not check for root linger

---

README.md
tasks/create_update_kube_spec.yml
tasks/create_update_quadlet_spec.yml
tasks/handle_user_group.yml
tests/tests_basic.yml

When creating host directories, do not use `become`, because if
it needs to change ownership, that must be done by `root`, not
as the rootless podman user.
In order to test this, I have changed the role to export the subuid and subgid
information for the rootless users as two dictionaries:
`podman_subuid_info` and `podman_subgid_info`.  See `README.md` for
usage.
NOTE that depending on the namespace used by your containers, you might not
be able to use the subuid and subgid information, which comes from `getsubids`
if available, or directly from the files `/etc/subuid` and `/etc/subgid` on
the host.
QE: The test tests_basic.yml has been extended for this.

fix: do not use become for changing hostdir ownership, and expose subuid/subgid info

---

tasks/cleanup_kube_spec.yml
tests/tests_basic.yml

Cause: The task that calls podman_play was not checking if the kube yaml
file existed when cleaning up.
Consequence: The task would give an error that the pod could not be
removed.
Fix: Do not attempt to remove the pod if the kube yaml file does not
exist.
Result: Calling the podman role repeatedly to remove a kube spec
will not fail and will not report changes for subsequent removals.
QE: tests_basic.yml has been changed to check for this case

fix: make kube cleanup idempotent

---

README.md
defaults/main.yml
tasks/handle_credential_files.yml
tasks/handle_user_group.yml
tasks/main.yml
tests/tests_auth_and_security.yml

Feature: The parameter podman_credential_files is used to provide containers-auth.json
files which allow authentication to registries.  See README.md for more infomation.
Reason: Users need a way to provide credential files for authenticating to private
registries.  Some operations may need to pull images from registries in an
automated or unattended way, and cannot use `registry_username` and `registry_password`.
Result: Users can provide registry credentials for automated and
unattended operations.

feat: support podman_credential_files

---

README.md
defaults/main.yml
tasks/create_update_kube_spec.yml
tasks/create_update_quadlet_spec.yml
tasks/handle_certs_d.yml
tasks/handle_credential_files.yml
tasks/handle_kube_spec.yml
tasks/handle_quadlet_spec.yml
tasks/main.yml
tests/tasks/setup_registry.yml
tests/tests_auth_and_security.yml
tests/tests_basic.yml
vars/main.yml

Feature: Add two new parameters:
podman_registry_certificates is a list of dict.  Each dict specifies the
certs and keys to use to connect to the specified registry using TLS and
optionally use certificate authentication.  More information can be found
in the manpage for containers-certs.d.
podman_validate_certs is a boolean which allows you to require or disable
TLS certificate checking (i.e. if you do not have a CA cert for
podman_registry_certificates and you still want to pull images from a TLS
enabled registry).  This corresponds to the parameter "validate_certs"
of the module containers.podman.podman_image.  You can also control
certificate validation by using podman_registries_conf to configure
the "insecure" parameter for a registry.
Reason: Users need to be able to configure the …

feat: manage TLS cert/key files for registry connections and validate certs

---

.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-plugin-scan.yml
.github/workflows/ansible-test.yml
.yamllint.yml
tests/tests_quadlet_demo.yml

The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …

ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

---

.ostree/packages-runtime-CentOS-10.txt
.ostree/packages-runtime-Fedora.txt
.ostree/packages-runtime-RedHat-10.txt
tasks/cleanup_quadlet_spec.yml
tests/files/quadlet-basic.network
tests/tests_quadlet_basic.yml
tests/tests_quadlet_demo.yml
vars/CentOS_10.yml
vars/Fedora.yml
vars/RedHat_10.yml

Cause: The code was using "systemd-" + name of quadlet for
the network name when removing networks.
Consequence: If the quadlet had a different NetworkName, the
removal would fail.
Fix: Grab the network quadlet file and grab the NetworkName from
the file to use to remove the network.
Result: The removal of quadlet networks will work both with and
without a custom NetworkName in the quadlet file.
This also adds a fix for el10 and Fedora which installs the iptables-nft
package to allow rootless podman to manage networks using nftables.

fix: grab name of network to remove from quadlet file

---

README.md
defaults/main.yml
tasks/cancel_linger.yml
tasks/cleanup_quadlet_spec.yml
tasks/handle_quadlet_spec.yml
tasks/manage_linger.yml
tasks/parse_quadlet_file.yml
tests/files/quadlet-basic.network
tests/tasks/cleanup_registry.yml
tests/templates/quadlet-demo-mysql.container.j2
tests/tests_quadlet_basic.yml
tests/tests_quadlet_demo.yml

Cause: The code was not managing network systemd quadlet units.
Consequence: Network systemd quadlet units were not being stopped and
disabled.  Subsequent runs would fail due to the network units not
being cleaned up properly.
Fix: The role manages network systemd quadlet units, including stopping
and removing.
Result: Systemd quadlet network units are properly cleaned up.
In addition - improve the removal of all types of quadlet resources,
and include code which can be used to test and debug quadlet resource
removal.

fix: proper cleanup for networks; ensure cleanup of resources

---

README.md
defaults/main.yml
tasks/main.yml
tasks/set_vars.yml

Enhancement: - Added a block to identify and handle reboots for transactional update systems on package changes. Update README.
Reason: Ensure necessary reboots are managed, as changes on transactional update systems are applied in a separate snapshot and require a reboot to take effect.
Result: Manages system reboots for transactional update systems when a package is installed.
Issue Tracker Tickets (Jira or BZ if any):na

feat: Handle reboot for transactional update systems

---

tests/tests_quadlet_basic.yml
tests/tests_quadlet_demo.yml

The images we currently use for quadlet testing are only available
on x86_64

test: skip quadlet tests on non-x86_64

---

tests/tasks/setup_registry.yml

Add ostree support to package use in tests

test: fix ostree support

---

README.md
tasks/handle_user_group.yml

Cause: The podman role was looking up groups in the subgid values, not
users.
Consequence: If the user name was different from the group name, the role
would fail to lookup the subgid values.
Fix: Ensure that the user is used to lookup the subgid values.
Result: The subgid values are looked up correctly.

fix: subgid maps user to gids, not group to gids

---

tasks/parse_quadlet_file.yml

Cause: __podman_quadlet_parsed was not converted to a list.
Consequence: On older versions of Ansible, the volumes from the kube yaml
were not removed when removing quadlets.
Fix: Convert __podman_quadlet_parsed to a list after parsing.
Result: Older versions of Ansible can remove volumes specified
in kube yaml files.

fix: Cannot remove volumes from kube yaml - need to convert yaml to list

---

tasks/cleanup_kube_spec.yml

Cause: The module uses the `podman kube play --done` command to remove
the pod specified by the kube spec, but does not check if the pod has
already been removed.  That is, it is not idempotent.  The command
gives an error if the pod is not found.  This only happens with
podman 4.4.1 on EL8.8 and EL9.2.
Consequence: The podman role gives an error that the pod specified
by the kube spec cannot be found when removing.
Fix: The role ignores the 'pod not found' error when removing
a kube spec.
Result: The role does not give an error when removing a kube
spec.
NOTE: This has been fixed in the containers.podman.podman_play
module upstream but has not yet been released.
https://github.com/containers/ansible-podman-collections/pull/863/files#diff-6672fb7f52e2bec3450c2dd7ed9a4385accd9bab8429ea6eecf …

fix: ignore pod not found errors when removing kube specs

---

tasks/cancel_linger.yml
tests/templates/quadlet-basic.network.j2
tests/tests_quadlet_basic.yml

Cause: Role was using podman and loginctl features not supported on el 8.8/9.2
and podman versions less than 4.7.0.  NetworkName and VolumeName not supported
until podman 4.7.0.  loginctl -P not supported in el 8.8/9.2.
Consequence: The role would give failures when managing el 8.8/9.2 machines.
Fix: Do not test with NetworkName and VolumeName when podman version is less
than 4.7.0.  Use loginctl --value -p instead of -P which will work on all
versions.
Result: The role can manage el 8.8/9.2 machines.

fix: make role work on el 8.8 and el 9.2 and podman version less than 4.7.0

---

README.md
tasks/cleanup_quadlet_spec.yml
tasks/handle_quadlet_spec.yml
tasks/main.yml
templates/systemd.j2
tests/tests_quadlet_pod.yml

Feature: Users can now specify quadlets of type `Pod`, and define containers
to run in pods.
Reason: Support for the `Pod` type is an important feature of podman 5, and
users want to use pods with containers.
Result: Users may specify quadlets of type `Pod` and run containers
in pods.
NOTE: Use of `Pod` requires podman version 5 or later.

feat: support for Pod quadlets

---

tests/tests_quadlet_pod.yml

tests_quadlet_pod.yml cleanup section was disabled - enable it

test: enable pod test cleanup

---

tasks/handle_secret.yml
tasks/handle_user_group.yml
tests/tests_quadlet_basic.yml

Cause: The code that handles secrets did not get user information for
users specified in `run_as_user`.
Consequence: The role gives an error when attempting to process secrets
which have `run_as_user`.
Fix: Get the user information for secrets that specify `run_as_user`.
Result: The role correctly handles secrets which specify `run_as_user`.

fix: get user information for secrets

---

templates/toml.j2

Cause: The code that formats options into TOML format does not convert boolean values to the correct string representation.
Consequence: Boolean options are not handled correctly.
Fix: Convert boolean options to string, then lower case, which is the correct TOML boolean format.
Result: Boolean options are correctly written and handled in TOML files.
Issue Tracker Tickets (Jira or BZ if any): Fixes Github #208

fix: render boolean option values correctly in toml files

---

tasks/handle_credential_files.yml
tasks/handle_policy_json.yml
tasks/handle_storage_conf.yml
tasks/main.yml
tests/tests_config_files.yml
vars/main.yml

Cause: The role was using two different modes for the common parent path
for various config files and authentication files.
Consequence: The role would change the parent path mode every time the role
is run if managing both authentication and config files.
Fix: Use a consistent mode for the parent path.
Result: The role does not report changed: true unnecessarily.
This fixes https://github.com/linux-system-roles/podman/issues/210
This changes the tests_config_files.yml to add an auth file to check
if the path mode is changed.

fix: Do not change the directory mode for the container parent path

---

filter_plugins/podman_to_toml.py

ansible-test does not like the use of unicode_literals
```
ERROR: Found 1 no-unicode-literals issue(s) which need to be resolved:
ERROR: plugins/filter/podman_to_toml.py:6:67: do not use `unicode_literals`
```
ansible-test requires field numbering in format specs:
```
ERROR: plugins/filter/podman_to_toml.py:135:20: ansible-format-automatic-specification: Format string contains automatic field numbering specification
ERROR: plugins/filter/podman_to_toml.py:160:50: ansible-format-automatic-specification: Format string contains automatic field numbering specification
```

refactor: fix ansible-test issues - unicode_literals, format string
